### ISSUE TITLE
Explain that first top layer is printed at "bridging speed"

### ISSUE THREAD

**Issue by theopensourcerer** [slic3r/Slic3r-Manual#46]
Please see https://github.com/prusa3d/Slic3r/issues/626 for some more details but just a note to suggest that it might be a good idea to explain somwhere that when you have any kind of fill that is not 100% the first top-layer is printed at bridging speed. 

This caught me by surprise when printing PETG ;-)

Thanks

**Comment by lordofhyphens** [comment]
It makes sense when you think about it at all though. Anything that has
free space underneath it must be at bridge flow (and ideally speed). There
is simply no concept of a layer height without something underneath it to
constrain it.

**Comment by theopensourcerer** [comment]
@lordofhyphens Yes. I do see that for sure. But this didn't happen in Cura. When the infill percentage is high enough that the gaps between the filament rows is small (< 1mm), bridging doesn't really matter surely? 

Maybe the bridge speed should be proportional to the length of the bridge ;-)

**Comment by lordofhyphens** [comment]
Since the Manual is all Markdown, submit a PR with the changes you think need to be made; requests to change the behavior of Slic3r (not Prusa3d Slic3r) go to https://github.com/slic3r/Slic3r/issues
