### ISSUE TITLE
TOC for Support material link isn't correct

### ISSUE THREAD

**Issue by DivingDuck** [slic3r/Slic3r-Manual#53]
A little mistake:
The TOC for Support material is directed to "support-material" w/o a dot where your id is
`<h4 id="support-material.">Support material.</h4>`

Correction:
`<h4 id="support-material">Support material</h4>`

**Comment by lordofhyphens** [comment]
It's all markdown,  so this is an easy pull request :)

**Comment by DivingDuck** [comment]
Thanks :)
